version: '3.8'

services:

  db:
    image: mysql
    container_name: city-delivery
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=city-delivery

  server:
    build:
      context: ./camellia
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - '8085:8085'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/camellia-cultivar
      - SPRING_DATASOURCE_DATABASE=city-delivery
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
